languageCode = "zh-cn"
languageName = "Simplified Chinese"
weight = 1
title = "海豚的博客"

[params]
  displayName = "CN"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  secondaryLogo = "img/secondary-logo.png"
  description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "圆润的海豚"
  image = "img/logo.jpg"
  # headline = "欢迎来到我的个人博客！"
  bio = "海阔凭鱼跃"
  links = [
    { email = "mailto:jou072@126.com" },
    { github = "https://github.com/username" },
    { instagram = "https://instagram.com/username" },
    { sina-weibo = "https://twitter.com/username" },
    { bilibili-fill = "https://space.bilibili.com/19446641" },
  ]
